
% simple import function generated via matlab import toolbox

function p2d = importp2d(filename)
%IMPORTFILE Import data from a text file
%  CAL3HALOGEN4PT5INCHOFFFLUME000001 = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the
%  numeric data.
%
%  CAL3HALOGEN4PT5INCHOFFFLUME000001 = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Cal3Halogen4pt5inchOffFlume000001 = importfile("D:\MAW_PHD_PIV\PhD_PS_Spr2021\Setup_2021-03-03a\V3V Calibration\Analysis\Cal3_Halogen4pt5inchOffFlume000001.T000.D000.P000.H000.V3VBA.p2d", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-Mar-2021 12:26:38

%% Input handling

% If dataLines is not specified, define defaults
dataLines = [3, Inf];

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["TitleDMAW_PHD_PIVPhD_PS_Spr2021Setup_20210303aV3VCalibrationAna", "Y", "Var3", "Var4", "Var5", "Var6"];
opts.SelectedVariableNames = ["TitleDMAW_PHD_PIVPhD_PS_Spr2021Setup_20210303aV3VCalibrationAna", "Y"];
opts.VariableTypes = ["double", "double", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var3", "Var4", "Var5", "Var6"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var3", "Var4", "Var5", "Var6"], "EmptyFieldRule", "auto");

% Import the data
p2d = readtable(filename, opts);

%% Convert to output type
p2d = table2array(p2d);
end